/**
 * Seed Data for EnglishApp Mobile
 * Dữ liệu mẫu từ backend migrations
 */

export const SEED_CATEGORIES = [
  {
    id: 'cat-toeic-001',
    name: 'TOEIC',
    slug: 'toeic',
    description: 'Từ vựng TOEIC',
    icon: '📚',
    color: '#3B82F6',
    sort_order: 1,
    is_active: 1,
  },
  {
    id: 'cat-ielts-001',
    name: 'IELTS',
    slug: 'ielts',
    description: 'Từ vựng IELTS',
    icon: '🎯',
    color: '#10B981',
    sort_order: 2,
    is_active: 1,
  },
  {
    id: 'cat-phrasal-001',
    name: 'Phrasal Verbs',
    slug: 'phrasal-verbs',
    description: 'Cụm động từ',
    icon: '💬',
    color: '#F59E0B',
    sort_order: 3,
    is_active: 1,
  },
  {
    id: 'cat-business-001',
    name: 'Business English',
    slug: 'business',
    description: 'Tiếng Anh thương mại',
    icon: '💼',
    color: '#8B5CF6',
    sort_order: 4,
    is_active: 1,
  },
  {
    id: 'cat-daily-001',
    name: 'Daily Conversation',
    slug: 'daily',
    description: 'Tiếng Anh giao tiếp hàng ngày',
    icon: '🗣️',
    color: '#EC4899',
    sort_order: 5,
    is_active: 1,
  },
  {
    id: 'cat-technology-001',
    name: 'Technology',
    slug: 'technology',
    description: 'Từ vựng công nghệ',
    icon: '💻',
    color: '#06B6D4',
    sort_order: 6,
    is_active: 1,
  },
  {
    id: 'cat-health-001',
    name: 'Health & Body',
    slug: 'health',
    description: 'Sức khỏe và cơ thể',
    icon: '🏥',
    color: '#EF4444',
    sort_order: 7,
    is_active: 1,
  },
  {
    id: 'cat-social-001',
    name: 'Social & Relationships',
    slug: 'social',
    description: 'Xã hội và các mối quan hệ',
    icon: '👥',
    color: '#F97316',
    sort_order: 8,
    is_active: 1,
  },
  {
    id: 'cat-family-001',
    name: 'Family',
    slug: 'family',
    description: 'Gia đình',
    icon: '👨‍👩‍👧‍👦',
    color: '#DB2777',
    sort_order: 9,
    is_active: 1,
  },
  {
    id: 'cat-study-001',
    name: 'Study & Learning',
    slug: 'study',
    description: 'Học tập và nghiên cứu',
    icon: '📖',
    color: '#7C3AED',
    sort_order: 10,
    is_active: 1,
  },
  {
    id: 'cat-travel-001',
    name: 'Travel',
    slug: 'travel',
    description: 'Du lịch',
    icon: '✈️',
    color: '#0891B2',
    sort_order: 11,
    is_active: 1,
  },
];

export const SEED_EXERCISE_TYPES = [
  {
    id: 'ext-mc-av-001',
    name: 'Multiple Choice Anh-Việt',
    slug: 'multiple_choice_anh_viet',
    description: 'Chọn nghĩa tiếng Việt từ tiếng Anh',
    config: JSON.stringify({ choices: 4, allow_hint: true }),
  },
  {
    id: 'ext-mc-va-001',
    name: 'Multiple Choice Việt-Anh',
    slug: 'multiple_choice_viet_anh',
    description: 'Chọn từ tiếng Anh từ nghĩa tiếng Việt',
    config: JSON.stringify({ choices: 4, allow_hint: true }),
  },
  {
    id: 'ext-fill-001',
    name: 'Fill in the Blank',
    slug: 'fill_blank',
    description: 'Điền từ còn thiếu vào câu',
    config: JSON.stringify({ allow_hint: true }),
  },
];

export const SEED_VOCABULARIES = [
  // TOEIC
  {
    id: 'voc-toeic-001',
    word: 'accommodate',
    meaning: 'chứa đựng, chứa được, cung cấp chỗ ở',
    pronunciation: '/əˈkɒmədeɪt/',
    example_sentence: 'This hotel can accommodate 200 guests.',
    example_translation: 'Khách sạn này có thể chứa 200 khách.',
    part_of_speech: 'verb',
    category_id: 'cat-toeic-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['hotel', 'business']),
  },
  {
    id: 'voc-toeic-002',
    word: 'agenda',
    meaning: 'chương trình nghị sự, nhật ký công việc',
    pronunciation: '/əˈdʒendə/',
    example_sentence: 'What is on the agenda for today?',
    example_translation: 'Chương trình hôm nay có gì?',
    part_of_speech: 'noun',
    category_id: 'cat-toeic-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['meeting', 'business']),
  },
  {
    id: 'voc-toeic-003',
    word: 'allocate',
    meaning: 'phân bổ, phân chia',
    pronunciation: '/ˈæləkeɪt/',
    example_sentence: 'We need to allocate more resources.',
    example_translation: 'Chúng ta cần phân bổ nhiều tài nguyên hơn.',
    part_of_speech: 'verb',
    category_id: 'cat-toeic-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['resource', 'management']),
  },
  {
    id: 'voc-toeic-004',
    word: 'alternative',
    meaning: 'sự lựa chọn thay thế',
    pronunciation: '/ɔːlˈtɜːnətɪv/',
    example_sentence: 'We have no alternative but to wait.',
    example_translation: 'Chúng ta không có lựa chọn nào khác ngoài việc chờ đợi.',
    part_of_speech: 'noun',
    category_id: 'cat-toeic-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['option']),
  },
  {
    id: 'voc-toeic-005',
    word: 'anticipate',
    meaning: 'đợi trước, đoán trước',
    pronunciation: '/ænˈtɪsɪpeɪt/',
    example_sentence: 'We anticipate a large crowd.',
    example_translation: 'Chúng tôi đoán sẽ có đông người.',
    part_of_speech: 'verb',
    category_id: 'cat-toeic-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['expect', 'predict']),
  },
  // IELTS
  {
    id: 'voc-ielts-001',
    word: 'comprehensive',
    meaning: 'toàn diện, đầy đủ',
    pronunciation: '/ˌkɒmprɪˈhensɪv/',
    example_sentence: 'This is a comprehensive study.',
    example_translation: 'Đây là một nghiên cứu toàn diện.',
    part_of_speech: 'adjective',
    category_id: 'cat-ielts-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['academic']),
  },
  {
    id: 'voc-ielts-002',
    word: 'demonstrate',
    meaning: 'chứng minh, diễn tả',
    pronunciation: '/ˈdemənstreɪt/',
    example_sentence: 'Can you demonstrate your theory?',
    example_translation: 'Bạn có thể chứng minh lý thuyết của mình không?',
    part_of_speech: 'verb',
    category_id: 'cat-ielts-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['academic', 'proof']),
  },
  {
    id: 'voc-ielts-003',
    word: 'enhance',
    meaning: 'tăng cường, cải thiện',
    pronunciation: '/ɪnˈhɑːns/',
    example_sentence: 'The course will enhance your skills.',
    example_translation: 'Khóa học này sẽ cải thiện kỹ năng của bạn.',
    part_of_speech: 'verb',
    category_id: 'cat-ielts-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['improve']),
  },
  {
    id: 'voc-ielts-004',
    word: 'fluctuate',
    meaning: 'dao động, lên xuống',
    pronunciation: '/ˈflʌktʃueɪt/',
    example_sentence: 'Prices fluctuate daily.',
    example_translation: 'Giá cả dao động hàng ngày.',
    part_of_speech: 'verb',
    category_id: 'cat-ielts-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['change', 'economics']),
  },
  {
    id: 'voc-ielts-005',
    word: 'inevitable',
    meaning: 'không thể tránh khỏi',
    pronunciation: '/ɪnˈevɪtəbl/',
    example_sentence: 'Change is inevitable.',
    example_translation: 'Sự thay đổi là không thể tránh khỏi.',
    part_of_speech: 'adjective',
    category_id: 'cat-ielts-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['certain']),
  },
  // Phrasal Verbs
  {
    id: 'voc-pv-001',
    word: 'break down',
    meaning: 'hỏng, trục trặc hoặc phân tích',
    pronunciation: null,
    example_sentence: 'My car broke down on the highway.',
    example_translation: 'Xe tôi bị hỏng trên đường cao tốc.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-phrasal-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['car', 'problem']),
  },
  {
    id: 'voc-pv-002',
    word: 'call off',
    meaning: 'hoãn, hủy bỏ',
    pronunciation: null,
    example_sentence: 'The meeting was called off.',
    example_translation: 'Cuộc họp đã bị hủy bỏ.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-phrasal-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['cancel', 'meeting']),
  },
  {
    id: 'voc-pv-003',
    word: 'carry out',
    meaning: 'tiến hành, thực hiện',
    pronunciation: null,
    example_sentence: 'The research was carried out carefully.',
    example_translation: 'Nghiên cứu được thực hiện cẩn thận.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-phrasal-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['execute', 'perform']),
  },
  {
    id: 'voc-pv-004',
    word: 'look forward to',
    meaning: 'mong chờ',
    pronunciation: null,
    example_sentence: 'I look forward to seeing you.',
    example_translation: 'Tôi mong chờ được gặp bạn.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-phrasal-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['expect', 'anticipate']),
  },
  {
    id: 'voc-pv-005',
    word: 'put off',
    meaning: 'hoãn lại',
    pronunciation: null,
    example_sentence: "Don't put off until tomorrow.",
    example_translation: 'Đừng hoãn đến ngày mai.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-phrasal-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['delay', 'postpone']),
  },
  // Business
  {
    id: 'voc-biz-001',
    word: 'revenue',
    meaning: 'doanh thu',
    pronunciation: '/ˈrevənjuː/',
    example_sentence: 'Our revenue increased this quarter.',
    example_translation: 'Doanh thu của chúng ta tăng trong quý này.',
    part_of_speech: 'noun',
    category_id: 'cat-business-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['finance', 'money']),
  },
  {
    id: 'voc-biz-002',
    word: 'merger',
    meaning: 'sự sáp nhập',
    pronunciation: '/ˈmɜːdʒə/',
    example_sentence: 'The merger was announced yesterday.',
    example_translation: 'Thương vụ sáp nhập được công bố hôm qua.',
    part_of_speech: 'noun',
    category_id: 'cat-business-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['acquisition']),
  },
  {
    id: 'voc-biz-003',
    word: 'stakeholder',
    meaning: 'cổ đông, bên liên quan',
    pronunciation: '/ˈsteɪkhəʊldə/',
    example_sentence: 'All stakeholders were informed.',
    example_translation: 'Tất cả các bên liên quan đã được thông báo.',
    part_of_speech: 'noun',
    category_id: 'cat-business-001',
    difficulty_level: 'advanced',
    tags: JSON.stringify(['shareholder']),
  },
  {
    id: 'voc-biz-004',
    word: 'negotiate',
    meaning: 'đàm phán',
    pronunciation: '/nɪˈɡəʊʃieɪt/',
    example_sentence: 'We need to negotiate the contract.',
    example_translation: 'Chúng ta cần đàm phán hợp đồng.',
    part_of_speech: 'verb',
    category_id: 'cat-business-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['agreement', 'deal']),
  },
  {
    id: 'voc-biz-005',
    word: 'quarterly',
    meaning: 'hàng quý',
    pronunciation: '/ˈkwɔːtəli/',
    example_sentence: 'We have quarterly meetings.',
    example_translation: 'Chúng ta có cuộc họp hàng quý.',
    part_of_speech: 'adjective',
    category_id: 'cat-business-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['frequency']),
  },
  // Daily
  {
    id: 'voc-daily-001',
    word: 'awkward',
    meaning: 'lúng túng, ngượng ngùng',
    pronunciation: '/ˈɔːkwəd/',
    example_sentence: 'It was an awkward situation.',
    example_translation: 'Đó là một tình huống lúng túng.',
    part_of_speech: 'adjective',
    category_id: 'cat-daily-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['feeling']),
  },
  {
    id: 'voc-daily-002',
    word: 'chill out',
    meaning: 'thư giãn, bình tĩnh lại',
    pronunciation: null,
    example_sentence: 'Just chill out and relax.',
    example_translation: 'Thôi thư giãn và bình tĩnh lại.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-daily-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['relax']),
  },
  {
    id: 'voc-daily-003',
    word: 'fancy',
    meaning: 'muốn, thích (đúng không)',
    pronunciation: '/ˈfænsi/',
    example_sentence: 'I fancy a pizza tonight.',
    example_translation: 'Tôi muốn ăn pizza tối nay.',
    part_of_speech: 'verb',
    category_id: 'cat-daily-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['want', 'desire']),
  },
  {
    id: 'voc-daily-004',
    word: 'gut feeling',
    meaning: 'linh cảm',
    pronunciation: null,
    example_sentence: 'Trust your gut feeling.',
    example_translation: 'Hãy tin vào linh cảm của bạn.',
    part_of_speech: 'noun',
    category_id: 'cat-daily-001',
    difficulty_level: 'intermediate',
    tags: JSON.stringify(['intuition']),
  },
  {
    id: 'voc-daily-005',
    word: 'hang out',
    meaning: 'đi chơi với bạn bè',
    pronunciation: null,
    example_sentence: "Let's hang out this weekend.",
    example_translation: 'Hãy đi chơi cuối tuần này nhé.',
    part_of_speech: 'phrasal_verb',
    category_id: 'cat-daily-001',
    difficulty_level: 'beginner',
    tags: JSON.stringify(['socialize']),
  },
];

export const SEED_EXERCISES = [
  {
    id: 'ex-toeic-001',
    title: 'TOEIC Vocabulary Test 1',
    description: 'Kiểm tra từ vựng TOEIC cơ bản',
    category_id: 'cat-toeic-001',
    exercise_type_id: 'ext-mc-av-001',
    difficulty: 'beginner',
    question_count: 10,
    pass_score: 70,
    is_active: 1,
  },
  {
    id: 'ex-ielts-001',
    title: 'IELTS Advanced Vocabulary',
    description: 'Từ vựng IELTS nâng cao - điền từ',
    category_id: 'cat-ielts-001',
    exercise_type_id: 'ext-fill-001',
    difficulty: 'advanced',
    question_count: 5,
    pass_score: 60,
    is_active: 1,
  },
  {
    id: 'ex-pv-001',
    title: 'Common Phrasal Verbs',
    description: 'Các phrasal verbs thông dụng',
    category_id: 'cat-phrasal-001',
    exercise_type_id: 'ext-mc-va-001',
    difficulty: 'intermediate',
    question_count: 5,
    pass_score: 70,
    is_active: 1,
  },
  {
    id: 'ex-biz-001',
    title: 'Business English Test',
    description: 'Kiểm tra từ vựng thương mại',
    category_id: 'cat-business-001',
    exercise_type_id: 'ext-mc-av-001',
    difficulty: 'intermediate',
    question_count: 5,
    pass_score: 70,
    is_active: 1,
  },
  {
    id: 'ex-daily-001',
    title: 'Daily Conversation',
    description: 'Tiếng Anh giao tiếp hàng ngày',
    category_id: 'cat-daily-001',
    exercise_type_id: 'ext-mc-av-001',
    difficulty: 'beginner',
    question_count: 5,
    pass_score: 70,
    is_active: 1,
  },
];

export default SEED_CATEGORIES;
